CREATE TABLE `tasks` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`description` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`done` TINYINT(3) NOT NULL DEFAULT '0',
	`createAt` TIMESTAMP NOT NULL DEFAULT (now()),
	PRIMARY KEY (`id`) USING BTREE
);